

spring:
  application:
    name: foo


server:
  port: 8181



resilience4j:
  circuitbreaker:
    instances:
      barService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    instances:
      barService:
        maxAttempts: 3
        waitDuration: 1s




