


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
           - Path=/accounts/**
          filters:
            - StripPrefix=1